spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: java
    password: java
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: validate
logging:
    file: log
    level.root: INFO
server:
     port: 8080

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
logging:
    file:
    level.root: OFF
server:
     port: 8080
