spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: java
    password: java
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: validate
  scheduling:
    fixed: 600000       # Run a job every 10 minutes
    cron: "0 0 1 * * ?" # Run a job every day at 1 a.m.
  security:
    usersByUsernameQuery: SELECT email as username, password, enabled FROM users WHERE email=?
    authoritiesByUsernameQuery: SELECT u.email as username, r.role as role FROM users u INNER JOIN user_role r ON(r.userid=u.userid) WHERE u.email=?
logging:
    file: log
    level.root: INFO
server:
     port: 8080

---

spring:
  profiles: setup
  jpa:
    hibernate.ddl-auto: create

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
  scheduling:
    fixed: 30000          # Run a job every 30 seconds
    cron: "30 * * * * ?"  # Run a job every 30th second
logging:
    file:
    level.root: OFF
server:
     port: 8080
